baseURL = "https://blogs.intimationinc.com/"
title = "Intimationinc Blog"
author = "Intimationinc Authors"
copyright = "Intimationinc"
paginate = 20
theme = "tailwind"
languageCode = "en"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  toc = false
  showReadingTime = false
  [params.header]
    logo = "logo.jpeg"

  [params.footer]
    since = 2024
    poweredby = false
  [params.widgets]
    categories = true
    tags = true
    recentposts = true
  [params.giscus]
    # Enable comments
    enabled = true
    # Comment provider:
    provider = "giscus"

    # Which page types are commentable?
    commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

    # Configuration of giscus
    repo = "intimationinc/blog.remote" # Repo where the comments will live
    repo_id = "R_kgDOLJTy-w" # Repo where the comments will live
    category = "General" # Repo where the comments will live
    category_id = "DIC_kwDOLJTy-84Cc7Qj" # Repo where the comments will live
    mapping = "pathname" # How Utterances will match comment to page
    label = "comment" # Label applied to issue by utteranc.es bot
    reactionsEnabled = 1
    emitMetadata = 1
  [params.social_media]
    [[params.social_media.items]]
      enabled = true
      title = 'Facebook'
      icon = 'brand-facebook'
      link = 'https://www.facebook.com/profile.php?id=61556296823994'
    [[params.social_media.items]]
      enabled = true
      title = 'Linkedin'
      icon = 'brand-linkedin'
      link = 'https://www.linkedin.com/company/intimationinc'
[menu]
  [[menu.main]]
    identifier = "Post"
    name = "Posts"
    pageRef = "/posts"
    weight = 0

  [[menu.main]]
    identifier = "extern"
    name = "Intimationinc"
    url = "https://remote.intimationinc.com"
    weight = 10
    [menu.main.params]
      rel = 'external'
