baseURL = "https://blogs.moficodes.dev/"
title = "moficodes"
author = "Mofi Rahman"
copyright = "moficodes"
paginate = 10
theme = "tailwind"
languageCode = "en"

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"
  toc = false
  showReadingTime = false
  [params.header]
    logo = "logo.png"

  [params.footer]
    since = 2024
    poweredby = false
  [params.widgets]
    categories = true
    tags = true
    recentposts = true
  [params.giscus]
    # Enable comments
    enabled = true
    # Comment provider:
    provider = "giscus"

    # Which page types are commentable?
    commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

    # Configuration of giscus
    repo = "moficodes/blogs" # Repo where the comments will live
    repo_id = "MDEwOlJlcG9zaXRvcnkzNTMxOTk1MjU=" # Repo where the comments will live
    category = "General" # Repo where the comments will live
    category_id = "DIC_kwDOFQ1lpc4CeWQ0" # Repo where the comments will live
    mapping = "pathname" # How Utterances will match comment to page
    label = "comment" # Label applied to issue by utteranc.es bot
    reactionsEnabled = 1
    emitMetadata = 1
  [params.social_media]
    [[params.social_media.items]]
      enabled = true
      title = 'Twitter'
      icon = 'brand-twitter'
      link = 'https://www.x.com/moficodes'
    [[params.social_media.items]]
      enabled = true
      title = 'Youtube'
      icon = 'brand-youtube'
      link = 'https://youtube.com/@containerbytes'
    [[params.social_media.items]]
      enabled = true
      title = 'Linkedin'
      icon = 'brand-linkedin'
      link = 'https://www.linkedin.com/in/moficodes'
[menu]
  [[menu.main]]
    identifier = "Post"
    name = "Posts"
    pageRef = "/posts"
    weight = 1

  [[menu.main]]
    identifier = "About"
    name = "About"
    pageRef = "/about"
    weight = 10
